repos:
  - repo: local
    hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      type: [python]
      args:
        [
          "-rn", # Only display messages
          "-sn", # Don't display the score
          "--rcfile=.pylintrc", # Link to your config file
          "--load-polugins=pylint.extensions.docparams" # Load an extension
        ]
   